repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - "--line-length=121"

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.2
    hooks:
      - id: pycln

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]


# flake8 is no longer supported on this repo: https://github.com/pre-commit/pre-commit-hooks
# after v2.5.0
# https://github.com/pre-commit/pre-commit-hooks/releases/tag/v2.5.0
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=121"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--extend-ignore=C901,E203,E266,E501,W503,w504,F403,F401,E402,E128"

